name = "EnergySystemModeling"
uuid = "2f1a2cda-0a35-11ea-0485-13adf048beb5"
authors = ["Jaan Tollander de Balsch <jaan.tollander@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"

[compat]
julia = ">=1.1"
