name = "EnergySystemModel"
uuid = "2f1a2cda-0a35-11ea-0485-13adf048beb5"
authors = ["Jaan Tollander de Balsch <jaan.tollander@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = ">=1.1"
